---
stages:
  - "Code Quality"
  - "Data update"

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5

.node_stage: &node_stage
  image: node:14-alpine
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - .yarn
  before_script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile

Quality tests:
  <<: *node_stage
  stage: "Code Quality"
  retry: 2
  script:
    - yarn test

Data fetch:
  <<: *node_stage
  only:
    - alpha
    - beta
    - master
    - next
  stage: "Data update"
  variables:
    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
    GIT_AUTHOR_NAME: Social Groovy Bot
    GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
    GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
    GIT_DEPTH: 4242
  before_script:
    - yarn --frozen-lockfile
    - yarn global add npx
    - apk update && apk add git
    - git config user.name "Social Groovy Bot"
    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  script:
    - yarn data:update
    - |
      if [[ -n "$(git status -s ./data)" ]]; then
        echo "Files changed, checking JSON validity"
        # Check JSON files
        for filename in ./data/*\.json; do
          node "$filename" > /dev/null || {
            echo "Invalid JSON in $filename"
            exit 1
          }
        done
        echo "Commit files"
        # Commit files
        NOW=$(date +"%Y%m%d_%H%M")
        git add data
        git commit -m "feat(data): $NOW update"
        git push --no-verify origin HEAD:master
        npx semantic-release
      else
        echo "Nothing changed"
      fi
