language: node_js
node_js:
  - "12"

cache:
  yarn: true

jobs:
  include:
    - stage: Test
      name: Unit Tests
      install:
        - yarn --frozen-lockfile
      script:
        - yarn test
      after_success:
        - npx codecov

# Limit branches builds to "master" one:
branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_success: never
